# Generated by Django 4.1.3 on 2022-12-21 00:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('uplode_by', models.CharField(max_length=25)),
            ],
        ),
    ]
