# Generated by Django 4.1.3 on 2022-12-28 06:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsite',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
