# Generated by Django 4.1.3 on 2022-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsiteapp', '0002_alter_blogsite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsite',
            name='description',
            field=models.TextField(),
        ),
    ]
